# DiscordMC by manuelgu
# https://manuelgu.eu
# https://www.spigotmc.org/resources/17067/
settings:
  token: 'TOKEN_HERE'
  send_game_login: true
  send_game_logout: true
  send_game_chat: true
  send_discord_chat: true
  send_death_message: true
  check_for_updates: true
  templates:
    chat_message_discord: '**%u**: %m'
    player_join_minecraft: '%u joined the game'
    player_leave_minecraft: '%u left the game'
    chat_message_minecraft: '<&b(discord [%c]) &r%u> %m'
  channels:
    # Channels below will receive messages from Minecraft
    minecraft_to_discord:
      - 'blah'
    # Channels below will send messages to Minecraft
    discord_to_minecraft:
      - 'blah'
  discord_commands:
    enabled: true
    command_prefix: '?'