name: ${project.name}
author: manuelgu
version: ${project.version}
main: ${project.groupId}.discordmc.${project.name}
description: ${project.description}
website: "https://www.spigotmc.org/resources/17067/"

commands:
  discord:
    description: Command for DiscordMC
    usage: /<command> <args>
